name: firebase_functions_interop_test
description: Test Firebase Functions Interop
version: 0.0.0
#homepage: https://www.example.com
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  firebase_functions_interop:
    path: ../

dev_dependencies:
  build_runner: ^0.7.8
  build_web_compilers:
    git:
      url: https://github.com/pulyaevskiy/build.git
      ref: node-support
      path: build_web_compilers