sudo: false

language: dart
dart:
  - dev

before_install:
  - nvm install 8.1.0
  - nvm use 8.1.0
  - node --version
  - npm install
  - npm install -g firebase-tools
  - ./tool/deploy.sh

script:
  - pub run test -p node -j 1 -r expanded
