sudo: false

language: dart
dart:
  - dev

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_script:
  - nvm install 8.1.0
  - nvm use 8.1.0
  - node --version
  - npm install
  - npm install -g firebase-tools
  - ./tool/deploy.sh

script:
  - pub run test -p node -j 1 -r expanded
