name: firebase_functions_interop
description: Write Firebase Cloud Functions in Dart
version: 1.0.0-dev.1.0
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  js: ^0.6.1
  node_interop: 
    git:
      url: git@github.com:pulyaevskiy/node-interop.git
      ref: dart20
  node_io:
    git:
      url: git@github.com:pulyaevskiy/node-io.git
      ref: master
  # firestore_interop: '>=0.0.1 <0.1.0'
  firebase_admin_interop: 
    git:
      url: git@github.com:pulyaevskiy/firebase-admin-interop.git
      ref: dart20

dev_dependencies:
  test: ^0.12.24
