name: firebase_functions_interop
description: JS interop library which allows writing Firebase Cloud Functions in Dart.
version: 1.0.0-dev.8.0
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  js: ^0.6.1
  node_interop: ^1.0.0-dev
  node_io: ^1.0.0-dev
  node_http: ^1.0.0-dev
  firebase_admin_interop: ^1.0.0-dev

dev_dependencies:
  test: ^1.0.0
