name: firebase_functions_interop
description: Write Firebase Cloud Functions in Dart
version: 0.0.2
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
  node_interop: ^0.0.4

dev_dependencies:
  test: ^0.12.24
  firebase_admin_interop: ^0.0.1

transformers:
  - $dart2js
  - node_interop
